---

# - name: "系统参数优化，禁用透明大页,改善redis变慢的问题"
#   template:
#     src: '{{ item.src }}'
#     dest: '{{ item.dest }}'
#     mode: '{{ item.mode }}'
#   loop:
#     - { src: 'rc.local.j2',dest: '/etc/rc.local',mode: '0755' }
- name: "系统参数优化，禁用透明大页,改善redis变慢的问题"
  shell: |
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
- {name: "standalone mode", include: install_single_redis.yml, when: groups.mids_first_three|length == 1}
- {name: "cluster mode", include: set_redis_cluster.yml, when: groups.mids_first_three|length > 1}