- name: app deploy path
  debug: var=deploy_path

- name: 清空应用部署目录
  file:
      path: "{{ deploy_path }}/modules"
      state: absent
  become: yes
  tags: ['upgrade']

- name: 检出应用部署文件
  shell: "svn checkout  {{ app_svn_path }}/modules {{ deploy_path }}/modules --username {{app_info.svn_username}} --password {{app_info.svn_password}} --non-interactive --trust-server-cert --no-auth-cache --force  warn=False"
  register: shell_out
  tags: ['upgrade']
- debug: var=shell_out.stderr_lines


- name: 停止服务
  shell: './stop.sh'
  args:
      chdir: "{{ deploy_path }}"
  register: stop_out
  tags: ['upgrade']
- debug: var=stop_out.stdout

- name: 启动服务
  shell: './startupByAnsible.sh'
  args:
      chdir: "{{ deploy_path }}"
  tags: ['upgrade']

- name: 等待3秒
  pause: seconds=3
  tags: ['upgrade']


- name: 查看日志
  shell: 'tail -20 {{ deploy_path }}/ms_logs/ms_all.log'
  register: app_console_out
  ignore_errors: true
  tags: ['upgrade']

- debug: var=app_console_out.stdout

