- name: app deploy path
  debug: var=deploy_path

- name: 清空应用部署目录
  file:
      path: "{{ deploy_path }}"
      state: absent
  become: yes
  tags: ['upgrade']

- name: 创建应用部署目录
  file:
      path: "{{ item.path }}"
      state: directory
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
  with_items:
      - { path: '{{ deploy_path }}', owner: 'winning', group: 'winning', mode: '0755' }
      - { path: '{{ deploy_path }}/launcher', owner: 'winning', group: 'winning', mode: '0755' }
      - { path: '{{ deploy_path }}/configure', owner: 'winning', group: 'winning', mode: '0755' }
  tags: ['upgrade']

- name: 检出应用部署文件
  shell: "svn checkout  {{ app_svn_path }}/modules {{ deploy_path }}/modules --username {{app_info.svn_username}} --password {{app_info.svn_password}} --non-interactive --trust-server-cert --no-auth-cache --force  warn=False"
  register: shell_out
  tags: ['upgrade']
- debug: var=shell_out.stderr_lines


- name: 拷贝配置文件
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: winning
      group: winning
      mode: 0755
  with_items:
      - { src: "stop.sh", dest: "{{ deploy_path }}/stop.sh" }
      - { src: "{{ app_info.application_file_name }}_{{ app_info.win_appid }}", dest: "{{ deploy_path }}/{{ app_info.application_file_name }}" }
  ignore_errors: true
  tags: ['upgrade']

- name: 拷贝启动Jar包
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: winning
      group: winning
      mode: 0755
  with_items:
      - { src: "stop.sh", dest: "{{ deploy_path }}/stop.sh" }
      - { src: "launcher/launch-0.0.1-SNAPSHOT.jar", dest: "{{ deploy_path }}/launcher/launch-0.0.1-SNAPSHOT.jar" }
      - { src: "configure/datasource.json", dest: "{{ deploy_path }}/configure/datasource.json" }
      - { src: "configure/emrdesigner.properties", dest: "{{ deploy_path }}/configure/emrdesigner.properties" }
      - { src: "configure/system.properties", dest: "{{ deploy_path }}/configure/system.properties" }
      - { src: "configure/datasource.json", dest: "{{ deploy_path }}/configure/datasource.json" }
      - { src: "configure/build-info.xml", dest: "{{ deploy_path }}/configure/build-info.xml" }
      - { src: "configure/build-metadata.xml", dest: "{{ deploy_path }}/configure/build-metadata.xml" }
      - { src: "configure/cleanIlog.properties", dest: "{{ deploy_path }}/configure/cleanIlog.properties" }
      - { src: "configure/logback.xml", dest: "{{ deploy_path }}/configure/logback.xml" }
      - { src: "configure/lui_params.json", dest: "{{ deploy_path }}/configure/lui_params.json" }
  tags: ['upgrade']

- name: 生成启动脚本
  template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: winning
      group: winning
      mode: 0755
  with_items:
      - { src: "startupByAnsible.sh.j2", dest: "{{ deploy_path }}/startupByAnsible.sh" }
      - { src: "startup.sh.j2", dest: "{{ deploy_path }}/startup.sh" }
  tags: ['upgrade']

- name: 停止服务
  shell: './stop.sh'
  args:
      chdir: "{{ deploy_path }}"
  register: stop_out
  tags: ['upgrade']
- debug: var=stop_out.stdout

- name: 启动服务
  shell: './startupByAnsible.sh'
  args:
      chdir: "{{ deploy_path }}"
  tags: ['upgrade']

- name: 等待3秒
  pause: seconds=3
  tags: ['upgrade']


- name: 查看日志
  shell: 'tail -20 {{ deploy_path }}/ms_logs/ms_all.log'
  register: app_console_out
  ignore_errors: true
  tags: ['upgrade']

- debug: var=app_console_out.stdout

