---
- name: init new system
  hosts: 'all:!cloudhost:!ops*'
  vars_files:
    - global_vars.yml
  vars:
    err_msgs: []
    title: "[{{inventory_hostname}}] {{ansible_ssh_host}}"
  pre_tasks:
    - name: "磁盘挂载预处理"
      script: "{{playbook_dir}}/mount_winning.sh"
      when: ansible_env_check|default(true) == true
    - include: env_check.yml
      when: ansible_env_check|default(true) == true
    - name: '环境不符合要求，则强制中止任务'
      fail: msg={{err_msgs|join(" ")}}
      when: err_msgs|length > 0
  roles:
    - {role: get_parameters, run_once: True, tags: ['params','get_parameters'], become: yes}
    - {role: os_init, become: yes}
    - {role: check_if_initialized, tags: ['check'], become: yes}
  post_tasks:
    - debug: "msg='{{inventory_hostname}}-主机初始化完成'"
