---
- name: install {{ soft_name }}
  yum:
    update_cache: yes
    name: '{{ soft_name }}'
    enablerepo: winning
    state: present

#- name: config {{ soft_name }} distributed cluster
#  template:
#    src: '{{ item.src }}'
#    dest: '{{ item.dest }}'
#  loop:
#    - { src: 'minio.j2', dest: '{{ conf_dir }}/minio' }
#  tags: config

- name: restart {{ soft_name }}
  systemd:
    name: '{{ soft_name }}'
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: init buckets
  script: "minio_init.sh"
