- name: app deploy path
  debug: var=deploy_path

- name: 生成启动脚本
  template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: winning
      group: winning
      mode: 0755
  with_items:
      - { src: "startupByAnsible.sh.j2", dest: "{{ deploy_path }}/startupByAnsible.sh" }
      - { src: "startup.sh.j2", dest: "{{ deploy_path }}/startup.sh" }
      - { src: "runByAnsible.sh.j2", dest: "{{ deploy_path }}/runByAnsible.sh" }
      - { src: "run.sh.j2", dest: "{{ deploy_path }}/run.sh" }
  when: app_info.generate_start_file is defined and app_info.generate_start_file == true
  tags: ['restart', 'stop']

- name: 停止服务
  shell: './stop.sh'
  args:
      chdir: "{{ deploy_path }}"
  register: stop_out
  when: app_info.module_type is match 'WINNING_MS*'
  ignore_errors: true
  tags: ['restart', 'stop']
- debug: var=stop_out.stdout

- name: 启动服务
  shell: './startupByAnsible.sh'
  args:
      chdir: "{{ deploy_path }}"
  when: app_info.module_type is match 'WINNING_MS*'
  tags: ['restart', 'start']

- name: 等待3秒
  pause: seconds=3
  tags: ['restart', 'start']

- name: 打印应用20行日志
  shell: 'tail -20 {{ log_path }}/console.log'
  register: app_console_out
  when: app_info.module_type != 'WINNING_MS_WDSFHIR' and app_info.deploy_type != 'aaiodepl'
  ignore_errors: true
  tags: ['install']
- debug: var=app_console_out.stdout
