- name: app deploy path
  debug: var=deploy_path

- name: stop java application
  shell: './stop.sh'
  args:
      chdir: "{{ deploy_path }}"
  register: stop_out
  when: app_info.module_type is match 'WINNING_MS*'
  ignore_errors: true
  tags: ['restart', 'stop']
- debug: var=stop_out.stdout

- name: startup java application
  shell: './startup.sh'
  args:
      chdir: "{{ deploy_path }}"
  when: app_info.module_type is match 'WINNING_MS*'
  tags: ['restart', 'start']

- name: wait 3s
  pause: seconds=3
  tags: ['restart', 'start']

- name: tail app console.log
  shell: 'tail -20 {{ log_path }}/console.log'
  register: app_console_out
  when: app_info.module_type != 'WINNING_MS_WDSFHIR'
  ignore_errors: true
  tags: ['install']
- debug: var=app_console_out.stdout

- name: tail wdsfhir app console.log
  shell: 'tail -20 {{log_wdsfhir_path}}'
  register: app_console_out
  when: app_info.module_type == 'WINNING_MS_WDSFHIR'
  ignore_errors: true
  tags: ['install']

- debug: var=app_console_out.stdout
