mode_change: True
h2_db_pass: "{{h2_db_pwd}}"
force: "yes"
svn_update_primary: "update PUBLIC.MISMGR_WEBCLIENT set PATCHVERSION=\\'{{revision_pair}}\\' where CLIENTIP=\\'{{app_master_ip}}\\' AND PROGRAMNAME=\\'{{item.app_name}}\\'"
svn_update_backup: "update PUBLIC.MISMGR_WEBCLIENT set PATCHVERSIONSEC=\\'{{revision_pair}}\\' where CLIENTIP=\\'{{app_master_ip}}\\' AND PROGRAMNAME=\\'{{item.app_name}}\\'"
svn_front_get_pri: "select PATCHVERSION from PUBLIC.MISMGR_WEBCLIENT where CLIENTIP=\\'{{app_master_ip}}\\' AND PROGRAMNAME=\\'{{item.app_name}}\\'"
svn_front_get_bak: "select PATCHVERSIONSEC from PUBLIC.MISMGR_WEBCLIENT where CLIENTIP=\\'{{app_master_ip}}\\' AND PROGRAMNAME=\\'{{item.app_name}}\\'"
