---
- name: checking if all mids is enabled
  hosts: all
  gather_facts: False
  vars:
   type: "check"
  tasks:
    - copy: src="{{playbook_dir}}/enable_mids.sh" dest=/tmp/ mode=0755
    - shell: "/tmp/enable_mid.sh {{type}}"
