- name: app deploy path
  debug: var=deploy_path

- name: 停止服务
  shell: './stop.sh'
  args:
      chdir: "{{ deploy_path }}"
  register: stop_out
  when: app_info.module_type is match 'WINNING_MS*'
  ignore_errors: true
  tags: ['stop']
- debug: var=stop_out.stdout
