---
# svn app path
app_svn_path: "{{ app_info.svn_path }}/{{ app_info.product_branch }}/{{ app_info.channel }}/{{ app_info.product_app_version }}"

# The application deploy path
deploy_path: "/winning/app/{{ app_info.repository_name }}/{{ app_info.win_app_version }}/{{ app_info.win_port }}"

# Java application with logback out file path
log_path: "/winning/log/{{ app_info.win_appid }}-{{ app_info.win_port }}/logs"

log_wdsfhir_path: "/winning/log/{{ app_info.win_port }}/logs/hl7.his/root.log"

WINAPPID: "{{ app_info.win_appid }}"
WINPORT: "{{ app_info.win_port }}"
CONSUL_TAG: "-Dspring.cloud.consul.discovery.tags={{ app_info.win_consul_tag }}"
INSTANCE_CODE: "-Dxxl.job.executor.port={{ app_info.xxl_job_port }}"
SERVER_PORT: "{{ app_info.win_port }}"
