- name: app deploy path
  debug: var=deploy_path

- name: 停止服务
  shell: './stop.sh'
  args:
      chdir: "{{ deploy_path }}"
  register: stop_out
  when: app_info.module_type is match 'WINNING_MS*'
  ignore_errors: true
  tags: ['uninstall']
- debug: var=stop_out.stdout

- name: 移除应用部署文件
  file:
      path: "{{ deploy_path }}"
      state: absent
  when: app_info.module_type is match 'WINNING_MS*'
  tags: ['uninstall']
