---
- name: install {{ soft_name }}
  yum:
    update_cache: yes
    name: '{{ soft_name }}'
    enablerepo: winning
    state: present

- name: server deployment
  include: server.yml
  when: "inventory_hostname|regex_search('mid')"
  tags: "server"
- name: agent deployment
  include: agent.yml
  when: "not inventory_hostname|regex_search('mid') and inventory_hostname|regex_search('app') and expanded_consul|default(false,true) == true" 
  tags: "agent"