---
- name: install {{ soft_name }}
  yum:
    update_cache: yes
    name: '{{ soft_name }}'
    enablerepo: winning
    state: present

- name: config {{ soft_name }} server
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'consul.j2', dest: '{{ conf_dir }}/consul' }
  tags: config

- name: restart {{ soft_name }}
  systemd:
    name: '{{ soft_name }}'
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags: restart

- name: '【wait for consul port 8500 open】'
  wait_for:
    port: 8500
    delay: 4
    timeout: 20

- name: create {{ soft_name }} cluster
  shell: consul join {{ mid_targets[0] }}
  when: inventory_hostname != mid_targets[0]
